version: '3'
services:
  nginx_container_1:
    image: nginx
    volumes:
      - type: volume
        source: my_volume
        target: /data/named_volume
      - type: bind
        source: "C:/Users/Henri Koch/Documents/M347/KN05/shared"
        target: /data
      - type: tmpfs
        target: "/data-tmpfs"

  nginx_container_2:
    image: nginx
    volumes:
      - my_volume:/data/named_volume:ro

volumes:
  my_volume:
